### PR TITLE
Generate both API and Scaffold with command scaffoldAPI

### PR DESCRIPTION
**Pull request by anand-patel**
added new command scaffoldAPI to generate API and scaffold view.

### CODE REVIEW

**Comment by mitulgolakiya** [comment]
Thanks @anand-patel,

I will review merge it and will do the next release out. v1.1

**Comment by fritzh321** [comment]
The scaffoldAPI command causes errors after the creation of the repository. Just to let you know :)

image

**Comment by mitulgolakiya** [comment]
@FritzH321,
I have fixed this thing and will be solved in next release which will be out by tomorrow. Just try to get the master branch if you want it early access. It contains various breaking changes. so it's better to wait for upgrade guide.
Or just remove the package completely and install it again. Don't forget to remove generator.php from config folder.

Let me know how it goes.

**Comment by fritzh321** [comment]
Pulled an early repo which caused the error. The repo i now pulled worked like a charm :+1: Thx

**Pull request merged**
