### PR TITLE
Support for Laravel 5.2

### PR DESCRIPTION
**Pull request by jonphipps**

### CODE REVIEW

**Comment by mitulgolakiya** [comment]
I will create one branch for 5.1 version and then merge it with master.

**Comment by rodelapena** [comment]
hi Mitul, 
when do you plan to merge this banch? are there still tests to run? thanks to both

**Comment by mitulgolakiya** [comment]
I will get it done soon once I'm back from holidays.

**Comment by pepijnolivier** [comment]
@mitulgolakiya @jonphipps 

In the commit posted below, `illuminate/support` 5.2 is now required.
Because of this, composer will always need to install laravel 5.2 (laravel 5.1 uses illuminate/support 5.1)

Why is illuminate/support 5.2 now required?
Can't we change this to `"illuminate/support": "~5.1"` ??

https://github.com/jonphipps/laravel-api-generator/commit/21dac85ef4d0bb08394d1657213c07be7643f264

**Comment by jonphipps** [comment]
Laravel's versioning is not semver compatible and the 5.2 api breaks 5.1, so it's a problem (see https://laraver.xyz/versions/v5.2.0-beta1). If the 5.2-compatible changes work with the 5.1 api, then ~5.1 would be great, but someone (not me at the moment) will have to test that.

**Comment by pepijnolivier** [comment]
Okay, well I propose that after testing, we should at least tag the last version that's compatible with laravel 5.1, and write this in the readme

**Pull request merged**
