### PR TITLE
Dingo/api integration

### PR DESCRIPTION
**Pull request by KIVagant**
Issues #40 (and #42 too)
See details in issue #40 
DO NOT MERGE THIS. [Related pull](https://github.com/dingo/api/pull/420) should be merged first.

Critical changes. You need increment package version to 2.0.

### CODE REVIEW

**Comment by KIVagant** [comment]
Two fixes squashed.

**Comment by KIVagant** [comment]
Ok, this pull now can be merged.

**Comment by mitulgolakiya** [comment]
@KIVagant,
Thanks, I will merge it soon. Actually I am also working on some features which I listed on trello board. so I am planning to do one major release out 1.4 with some great new features.

**Comment by KIVagant** [comment]
@mitulgolakiya, merge can be hard, If you will try to make it after some changes to master.

**Comment by mitulgolakiya** [comment]
I will merge it today only in master. Then I will integrate my changes.

**Pull request merged**
